# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-10-25 14:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_module_enrolled_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='price',
            field=models.PositiveIntegerField(),
        ),
    ]
