# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-11-20 15:47
from __future__ import unicode_literals

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_auto_20181025_1533'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='language',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='language',
            name='framework',
        ),
        migrations.AddField(
            model_name='language',
            name='description',
            field=tinymce.models.HTMLField(blank=True),
        ),
        migrations.AlterField(
            model_name='module',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.DeleteModel(
            name='Framework',
        ),
    ]
