# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-11-20 15:50
from __future__ import unicode_literals

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_auto_20181120_1547'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='description',
            field=tinymce.models.HTMLField(blank=True),
        ),
    ]
