# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-11-24 17:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_module_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='release_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
