# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-10-19 21:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='display_name',
            field=models.CharField(default=b'Anonymous', max_length=40),
        ),
    ]
