# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-12-02 15:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20181202_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/blogs/post'),
        ),
    ]
